from enum import Enum as PyEnum

class RoleName(PyEnum):
    OVERALL_COORDINATOR = "overall coordinator"
    COORDINATOR = "coordinator"
    EXECUTIVE = "executive"
    GENERAL_SECRETARY = "general secretary"
    DEPUTY_GENERAL_SECRETARY = "deputy general secretary"
    SECRETARY = "secretary"
    CONVENER = "convener"
    PRESIDENT = "president"
    VICE_PRESIDENT = "vice president"
    TEAM_HEAD = "team head"
    ACHEAD = "achead"

class OrgType(PyEnum):
    CLUB = "club"
    BOARD = "board"
    SOCIETY = "society"
    FEST = "fest"
    SPORT = "sport"
    DEPARTMENT = "department"

class DepartmentName(PyEnum):
    APPLIED_MECHANICS = "Applied Mechanics"
    BIOCHEMICAL_ENGINEERING_AND_BIOTECHNOLOGY = "Biochemical Engineering and Biotechnology"
    CHEMICAL_ENGINEERING = "Chemical Engineering"
    CHEMISTRY = "Chemistry"
    CIVIL_ENGINEERING = "Civil Engineering"
    COMPUTER_SCIENCE_AND_ENGINEERING = "Computer Science and Engineering"
    DESIGN = "Design"
    ELECTRICAL_ENGINEERING = "Electrical Engineering"
    ENERGY_SCIENCE_AND_ENGINEERING = "Energy Science and Engineering"
    HUMANITIES_AND_SOCIAL_SCIENCES = "Humanities and Social Sciences"
    MANAGEMENT_STUDIES = "Management Studies"
    MATERIALS_SCIENCE_AND_ENGINEERING = "Materials Science and Engineering"
    MATHEMATICS = "Mathematics"
    MECHANICAL_ENGINEERING = "Mechanical Engineering"
    PHYSICS = "Physics"
    TEXTILE_AND_FIBRE_ENGINEERING = "Textile and Fibre Engineering"

class HostelName(PyEnum):
    ARAVALI = "Aravali"
    DRONAGIRI = "Dronagiri"
    GIRNAR = "Girnar"
    HIMADRI = "Himadri"
    JWALAMUKHI = "Jwalamukhi"
    KAILASH = "Kailash"
    KARAKORAM = "Karakoram"
    KUMAON = "Kumaon"
    NALANDA = "Nalanda"
    NILGIRI = "Nilgiri"
    SATPURA = "Satpura"
    SAHYADRI = "Sahyadri"
    SAPTAGIRI = "Saptagiri"
    SHIVALIK = "Shivalik"
    UDAIGIRI = "Udaigiri"
    VINDHYACHAL = "Vindhyachal"
    ZANSKAR = "Zanskar"
    DAYSCHOLAR = "Dayscholar"

class OrgName(PyEnum):
    # Apex Councils / Boards
    STUDENT_AFFAIRS_COUNCIL = "student affairs council"
    BOARD_FOR_HOSTEL_MANAGEMENT = "board for hostel management"
    BOARD_FOR_STUDENT_WELFARE = "board for student welfare"
    BOARD_FOR_SPORTS_ACTIVITIES = "board for sports activities"
    BOARD_FOR_RECREATIONAL_AND_CREATIVE_ACTIVITIES = "board for recreational and creative activities"
    BOARD_FOR_STUDENT_PUBLICATIONS = "board for student publications"
    CO_CURRICULAR_AND_ACADEMIC_INTERACTION_COUNCIL = "co-curricular and academic interaction council"

    # CAIC Technical Clubs
    DEVCLUB = "devclub"
    ROBOTICS_CLUB = "robotics club"
    AEROMODELLING_CLUB = "aeromodelling club"
    BUSINESS_AND_CONSULTING_CLUB = "business and consulting club"
    ECONOMICS_CLUB = "economics club"
    PHYSICS_AND_ASTRONOMY_CLUB = "physics and astronomy club"
    ALGORITHMS_AND_COMPUTING_CLUB = "algorithms and computing club"
    ARIES = "aries"
    IGEM = "igem"
    HYPERLOOP_CLUB = "hyperloop club"
    INDIAN_GAME_THEORY_SOCIETY = "indian game theory society"
    BLOCKCHAIN_SOCIETY = "blockchain society"
    AXLR8R_FORMULA_RACING = "axlr8r formula racing"

    # Academic / Departmental Societies
    MATHSOC = "mathsoc"
    ACES_ACM = "aces acm"
    BETA = "beta"
    MSES = "mses"
    CEF = "cef"
    MES = "mes"
    CHES = "ches"
    ENERGY_SOCIETY = "energy society"
    PHYSOC = "physoc"
    EES = "ees"
    TES = "tes"
    CHEMOCRONIES = "chemocronies"

    # BRCA Cultural Clubs
    MUSIC_CLUB = "music club"
    DANCE_CLUB = "dance club"
    DRAMATICS_CLUB = "dramatics club"
    LITERARY_CLUB = "literary club"
    DEBATING_CLUB = "debating club"
    PHOTOGRAPHY_AND_FILMS_CLUB = "photography and films club"
    FINE_ARTS_AND_CRAFTS_CLUB = "fine arts and crafts club"
    DESIGN_CLUB = "design club"
    QUIZZING_CLUB = "quizzing club"
    HINDI_SAMITI = "hindi samiti"
    SPIC_MACAY = "spic macay"
    ENVOGUE = "envogue"

    # Independent Student Groups
    INDRADHANU = "indradhanu"

    # Fests
    RENDEZVOUS = "rendezvous"
    TRYST = "tryst"
    BECON = "becon"
    LITERATI = "literati"
    SPORTECH = "sportech"

    # Sports
    AQUATICS = "aquatics"
    ATHLETICS = "athletics"
    BADMINTON = "badminton"
    BASKETBALL = "basketball"
    CHESS = "chess"
    CRICKET = "cricket"
    FOOTBALL = "football"
    HOCKEY = "hockey"
    LAWN_TENNIS = "lawn tennis"
    SQUASH = "squash"
    TABLE_TENNIS = "table tennis"
    VOLLEYBALL = "volleyball"
    WEIGHTLIFTING = "weightlifting"
    
    # Departments (can also exist as organizations, eg for posting their own events if separate from caic societies)
    APPLIED_MECHANICS = "applied mechanics"
    BIOCHEMICAL_ENGINEERING_AND_BIOTECHNOLOGY = "biochemical engineering and biotechnology"
    CHEMICAL_ENGINEERING = "chemical engineering"
    CHEMISTRY = "chemistry"
    CIVIL_ENGINEERING = "civil engineering"
    COMPUTER_SCIENCE_AND_ENGINEERING = "computer science and engineering"
    DESIGN = "design"
    ELECTRICAL_ENGINEERING = "electrical engineering"
    ENERGY_SCIENCE_AND_ENGINEERING = "energy science and engineering"
    HUMANITIES_AND_SOCIAL_SCIENCES = "humanities and social sciences"
    MANAGEMENT_STUDIES = "management studies"
    MATERIALS_SCIENCE_AND_ENGINEERING = "materials science and engineering"
    MATHEMATICS = "mathematics"
    MECHANICAL_ENGINEERING = "mechanical engineering"
    PHYSICS = "physics"
    TEXTILE_AND_FIBRE_ENGINEERING = "textile and fibre engineering"